

a = Neutral.new;

Neutral.findRespondingMethodFor(\doesNotUnderstand)

Neutral.respondingMethodSelectors



/////////
// some misunderstanding here.

NeutralizeObject.write(Neutral);
NeutralizeObject.write(NeutralTest);




Neutral.overriddenMethodSelectors



Neutral.respondingMethods.first.findReferences(\doesNotUnderstand)

Neutral.findRespondingMethodFor(\do).findReferences(\doesNotUnderstand)

Neutral.respondingMethods.first.findReferences(\doesNotUnderstand)


Neutral.findRespondingMethodFor(\do).findReferences(\doesNotUnderstand)
Object.findRespondingMethodFor(\do).findReferences(\doesNotUnderstand)


Neutral.findRespondingMethodFor(\cyc).findReferences(\doesNotUnderstand)

Neutral.findRespondingMethodFor(\cyc).findReferences(\embedInStream)
Object.findRespondingMethodFor(\cyc).findReferences(\embedInStream)


SequenceableCollection.findRespondingMethodFor(\indexIn).findReferences(\indexOfGreaterThan)


